name: Publish Nuget Packages

on:
  push:
    tags:
      - "*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x

      # Versions
      - uses: dotnet/nbgv@master
        id: rtk_version
        with:
          setAllVars: true

      # Publish RTK
      - name: Build Packages
        run: |
          dotnet restore .\CustomExtensions.WinUI\CustomExtensions.WinUI.csproj
          dotnet build -p:Configuration=Release .\CustomExtensions.WinUI\CustomExtensions.WinUI.csproj

      # NuGet Push
      - name: Push package to Nuget registry
        run: |
          dotnet nuget push "..\NugetPackages\kitUIN.CustomExtensions.WinUI.*.nupkg" --api-key $NUGET_KEY --source https://api.nuget.org/v3/index.json
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          # automatic_release_tag: ${{ github.ref_name }}
          title: ${{ github.ref_name }}
          prerelease: false
          # files: |
          #   build/libs/*